import { Notification } from '@/types/notification';
import { subDays, subHours, subMinutes } from 'date-fns';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'message',
    priority: 'high',
    title: 'New message from John Doe',
    message: 'Hey, I wanted to discuss the training schedule for next week. Are you available?',
    timestamp: subMinutes(new Date(), 5),
    read: false,
    senderName: 'John Doe',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: '2',
    type: 'achievement',
    priority: 'medium',
    title: 'Team milestone reached! 🎉',
    message: 'Your team has completed 100 training sessions this month. Great work!',
    timestamp: subHours(new Date(), 2),
    read: false,
  },
  {
    id: '3',
    type: 'reminder',
    priority: 'medium',
    title: 'Training session starting soon',
    message: 'You have a training session scheduled in 30 minutes with Team Alpha.',
    timestamp: subHours(new Date(), 3),
    read: true,
    readAt: subHours(new Date(), 2),
    actionUrl: '/sessions/123',
    actionLabel: 'View Session',
  },
  {
    id: '4',
    type: 'system',
    priority: 'low',
    title: 'System maintenance scheduled',
    message: 'The app will undergo maintenance on Sunday, 2:00 AM - 4:00 AM EST.',
    timestamp: subHours(new Date(), 8),
    read: true,
    readAt: subHours(new Date(), 6),
  },
  {
    id: '5',
    type: 'warning',
    priority: 'high',
    title: 'Action required: Incomplete roster',
    message: 'Please complete your team roster before the next training session.',
    timestamp: subDays(new Date(), 1),
    read: false,
    actionUrl: '/roster',
    actionLabel: 'Update Roster',
  },
  {
    id: '6',
    type: 'info',
    priority: 'low',
    title: 'New feature available',
    message: 'Check out the new analytics dashboard to track your team performance.',
    timestamp: subDays(new Date(), 1),
    read: true,
    readAt: subHours(new Date(), 20),
    actionUrl: '/analytics',
    actionLabel: 'Explore',
  },
  {
    id: '7',
    type: 'message',
    priority: 'medium',
    title: 'Sarah Smith commented on your report',
    message: 'Great analysis! Can you add more details about the defensive strategies?',
    timestamp: subDays(new Date(), 2),
    read: true,
    readAt: subDays(new Date(), 1),
    senderName: 'Sarah Smith',
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: '8',
    type: 'achievement',
    priority: 'low',
    title: 'Weekly goal achieved',
    message: 'You have logged all training sessions for this week. Keep it up!',
    timestamp: subDays(new Date(), 3),
    read: true,
    readAt: subDays(new Date(), 2),
  },
];